FROM openjdk:11

ENV SPRING_BOOT_APP_JAVA_OPTS -Xms256m -Xmx1024m

ENV SPRING_BOOT_APP modernjava-0.0.1.jar
ENV SPRING_BOOT_APP_PATH /opt/$SPRING_BOOT_APP

COPY ./target/$SPRING_BOOT_APP $SPRING_BOOT_APP_PATH

EXPOSE 8888

ENTRYPOINT java $SPRING_BOOT_APP_JAVA_OPTS -jar $SPRING_BOOT_APP_PATH $SPRING_BOOT_APP_OPTS